export const links = {
  docs: {
    eMode: 'https://docs.spark.fi/user-guides/using-sparklend/e-mode',
    isolationMode: 'https://docs.spark.fi/user-guides/using-sparklend/#isolation-mode',
    siloedMode: 'https://docs.spark.fi/user-guides/using-sparklend/#supply-and-borrow-caps',
    isolationModeBorrowingPower: 'https://docs.spark.fi/user-guides/using-sparklend/isolation-mode',
    supplyBorrowCaps: 'https://docs.spark.fi/user-guides/using-sparklend/#supply-and-borrow-caps',
    dsr: 'https://docs.spark.fi/user-guides/earning-savings/savings-dai#what-is-the-dai-savings-rate',
    ssr: 'https://docs.spark.fi/user-guides/earning-savings/savings-usds#what-is-the-sky-savings-rate',
    upgradeDai: 'https://docs.spark.fi/user-guides/upgrading-to-usds-and-susds/upgrading-to-usds',
    upgradeSdai: 'https://docs.spark.fi/user-guides/upgrading-to-usds-and-susds/upgrading-to-susds',
    downgradeUsds: 'https://docs.spark.fi/user-guides/upgrading-to-usds-and-susds/downgrading-to-dai',
    newSavings: 'https://docs.spark.fi/user-guides/upgrading-to-usds-and-susds',
    healthFactor: 'https://docs.spark.fi/user-guides/using-sparklend/borrowing-assets#what-is-the-health-factor',
    supplying: 'https://docs.spark.fi/user-guides/using-sparklend/depositing-assets#how-much-will-i-earn',
    borrowing: 'https://docs.spark.fi/user-guides/using-sparklend/borrowing-assets#how-much-will-i-pay-in-interest',
    sparkAirdrop: 'https://docs.spark.fi/governance/spk-token',
    farmingRewards: 'https://docs.spark.fi/user-guides/farming-rewards',
  },
  aaveTechnicalPaper: 'https://github.com/aave/aave-v3-core/blob/master/techpaper/Aave_V3_Technical_Paper.pdf',
  termsOfUse: 'https://spark.fi/terms-of-use',
  privacyPolicy: 'https://spark.fi/privacy-policy',
  github: 'https://github.com/marsfoundation/spark-app',
} as const
