export const capAutomatorAbi = [
  {
    inputs: [{ internalType: 'address', name: 'poolAddressesProvider', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'asset', type: 'address' }],
    name: 'RemoveBorrowCapConfig',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'asset', type: 'address' }],
    name: 'RemoveSupplyCapConfig',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'max', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'gap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'increaseCooldown', type: 'uint256' },
    ],
    name: 'SetBorrowCapConfig',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'max', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'gap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'increaseCooldown', type: 'uint256' },
    ],
    name: 'SetSupplyCapConfig',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'oldBorrowCap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newBorrowCap', type: 'uint256' },
    ],
    name: 'UpdateBorrowCap',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'oldSupplyCap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newSupplyCap', type: 'uint256' },
    ],
    name: 'UpdateSupplyCap',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'borrowCapConfigs',
    outputs: [
      { internalType: 'uint48', name: 'max', type: 'uint48' },
      { internalType: 'uint48', name: 'gap', type: 'uint48' },
      { internalType: 'uint48', name: 'increaseCooldown', type: 'uint48' },
      { internalType: 'uint48', name: 'lastUpdateBlock', type: 'uint48' },
      { internalType: 'uint48', name: 'lastIncreaseTime', type: 'uint48' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'exec',
    outputs: [
      { internalType: 'uint256', name: 'newSupplyCap', type: 'uint256' },
      { internalType: 'uint256', name: 'newBorrowCap', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'execBorrow',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'execSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pool',
    outputs: [{ internalType: 'contract IPool', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolConfigurator',
    outputs: [{ internalType: 'contract IPoolConfigurator', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'removeBorrowCapConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'removeSupplyCapConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'address', name: 'asset', type: 'address' },
      { internalType: 'uint256', name: 'max', type: 'uint256' },
      { internalType: 'uint256', name: 'gap', type: 'uint256' },
      { internalType: 'uint256', name: 'increaseCooldown', type: 'uint256' },
    ],
    name: 'setBorrowCapConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'asset', type: 'address' },
      { internalType: 'uint256', name: 'max', type: 'uint256' },
      { internalType: 'uint256', name: 'gap', type: 'uint256' },
      { internalType: 'uint256', name: 'increaseCooldown', type: 'uint256' },
    ],
    name: 'setSupplyCapConfig',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'supplyCapConfigs',
    outputs: [
      { internalType: 'uint48', name: 'max', type: 'uint48' },
      { internalType: 'uint48', name: 'gap', type: 'uint48' },
      { internalType: 'uint48', name: 'increaseCooldown', type: 'uint48' },
      { internalType: 'uint48', name: 'lastUpdateBlock', type: 'uint48' },
      { internalType: 'uint48', name: 'lastIncreaseTime', type: 'uint48' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
