export const migrationActionsAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_sdai', type: 'address', internalType: 'address' },
      { name: '_susds', type: 'address', internalType: 'address' },
      { name: '_daiJoin', type: 'address', internalType: 'address' },
      { name: '_usdsJoin', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'dai',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'daiJoin',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract JoinLike' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'downgradeUSDSToDAI',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assetsIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateDAIToUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assetsIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateDAIToSUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assetsIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'sharesOut', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateSDAIAssetsToUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assetsIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateSDAIAssetsToSUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assetsIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'sharesOut', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateSDAISharesToUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'sharesIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'assetsOut', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateSDAISharesToSUSDS',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'sharesIn', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'sharesOut', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'usds',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'usdsJoin',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract JoinLike' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sdai',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC4626' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'susds',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC4626' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vat',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract VatLike' }],
    stateMutability: 'view',
  },
] as const
