name: Release package (common-testnets)

on:
  push:
    branches:
      - main
    paths:
      - "packages/common-testnets/**"
      - ".github/workflows/release-canary-common-testnets.yml"

jobs:
  release-canary:
    strategy:
      matrix:
        node: [ "20" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install

      - run: pnpm build

      - name: Set version
        run: |
          cd packages/common-testnets
          npm pkg set version=0.2.0-canary.$(date +'%Y%m%d').$(git rev-parse --short HEAD)

          # update workspace dependencies to point to any version
          jq '.dependencies |= with_entries(if .value == "workspace:^" then .value = "*" else . end)' package.json > temp.json && mv temp.json package.json

          echo "Version changed: $(npm pkg get version)"

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          package: packages/common-testnets/package.json
          token: ${{ secrets.NPM_TOKEN_PHOENIX_LABS_BOT }}
          dry-run: false
          tag: canary
